import dns from './dns.js';
import ssl from './ssl.js';
import site from './site.js';
import tcping from './tcping.js';
import ping from './ping.js';
import domain from './domain.js';
import robots from './robots.js';
import favicon from './favicon.js';
import links from './links.js';
import tld from './tld.js';
import headers from './headers.js';
import { emailSecurity, emailCheck } from './email.js';
import rss from './rss.js';
import webContent from './webpage.js';
import crawl from './crawl.js';
import appstore from './appstore.js';
import probe from './probe.js';
import dnsPropagation from './propagation.js';
import batchCheck from './batch.js';
import ipReputation from './iprep.js';

export default [dns, ssl, site, tcping, ping, domain, robots, favicon, links, tld, headers, emailSecurity, emailCheck, rss, webContent, crawl, appstore, probe, dnsPropagation, batchCheck, ipReputation];
